### ISSUE TITLE
Add testing to verify support for numeric types

### ISSUE THREAD

**Issue by hannobraun** [flott-motion/ramp-maker#25]
The unit tests use `f32`, for the sake of convenience (and because it works pretty well on the platforms these unit tests run on). This is fine, but it makes it pretty easy to accidentally introduce trait bounds that are not supported by the fixed-point types, and manual testing is required to catch this.

#4 proposes a testing approach that would address this, but as an intermediate step, it would be fine to have some code that just tries to instantiate the motion profile implementations with each supported type, so we'll at least know at compile time if something breaks.

**Comment by jmwill86** [comment]
@hannobraun  I know a lot of these issues are a little older now, happy to try and work on this issue if it's still of use?

**Comment by hannobraun** [comment]
Hey @jmwill86! I'm still passively maintaining this repository, and I'm happy to merge changes that are of use to you. If you're asking whether working on this issue will be useful to me or anyone else, I don't know. Definitely not to me, and I have no indication that anyone else is using this project either. If people are, they are not making themselves known.

**Comment by hannobraun** [comment]
This library is no longer actively developed (and hasn't been for a while). I'm closing any issues that don't relate to specific gaps in existing functionality, as to not make the wrong impression about what is planned and desired.
