### ISSUE TITLE
Add support for velocity mode

### ISSUE THREAD

**Issue by hannobraun** [flott-motion/ramp-maker#34]
The current `MotionProfile` trait only supports moving to a specified position. There should be an additional interface that allows moving at a specific velocity, without a target position:

``` rust
pub trait MotionProfile {
    // ...
    fn enter_velocity_mode(&mut self, target_velocity: Self::Velocity);
}
```

The trapezoidal ramp generation algorithm should already be able to support this, with some minor prodding. In fact, I think velocity mode can be simulated using position mode, by setting a far-away target step:

``` rust
profile.enter_position_mode(target_velocity, 100_000);
```

And then making sure to repeat that call often enough, so the target step is never actually reached.

**Comment by nviennot** [comment]
That's a great idea!
I would use it

**Comment by hannobraun** [comment]
Thanks for your feedback. I have no plans to work on this, but a pull request would be very welcome.

**Comment by hannobraun** [comment]
This library is no longer actively developed (and hasn't been for a while). I'm closing any issues that don't relate to specific gaps in existing functionality, as to not make the wrong impression about what is planned and desired.
